version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pair-aws"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1nmmi6gvzqdht"
s3_prefix = "pair-aws"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
